version: '3.7'

services:
  # api:
  #   tty: true
  #   init: true
  #   image: node:14.15-alpine
  #   working_dir: /api
  #   volumes:
  #     - .:/invoicing:cached
  #     - ./node_modules:/invoicing/node_modules:delegated
  #     - yarn-cache:/.yarn-cache
  #   environment:
  #     NEW_RELIC_ENABLED: ${NEW_RELIC_ENABLED-0}
  #     NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY-(unset)}
  #     NODE_ENV: development
  #     TERMINUS_TIMEOUT: 1000
  #     TERMINUS_SHUTDOWN_DELAY: 0
  #     YARN_CACHE_FOLDER: /.yarn-cache

  rest:
    tty: true
    build: ./rest/dev
    working_dir: /rest
    volumes:
      - ./rest:/rest:cached
    environment:
      APACHE_DOCUMENT_ROOT: /rest/public
      JSON_KEY_FILE_ROOT: ${JSON_KEY_FILE_ROOT}
    ports:
      - "59087:80"
